version: '3.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  app:
    depends_on:
      - db
    image: demo-rest-2-image
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres
    ports:
      - "8080:8080"